MVCLab2/Controllers/TerritoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCLab2.Servicio;

namespace MVCLab2.Controllers
{
    public class TerritoryController : Controller
    {

        private ServicioClient servicio = new ServicioClient();

        public ActionResult Index()
        {
            ViewBag.listCustomerTerritory = servicio.ObtenerClientes();
           // ViewBag.listCustomerTerritory = servicio.ObtenerClientesNombreCliente("Gustavo");

            return View();
        }

        public ActionResult Search(FormCollection fc)
        {
            string condition = fc["condition"];
            string keyword = fc["keyword"];
            if (condition.Equals("byID"))
                ViewBag.listCustomerTerritory = servicio.ObtenerClientesNombreCliente(Convert.ToString(keyword));
            else
                if (condition.Equals("All"))
                    ViewBag.listCustomerTerritory = servicio.ObtenerClientes();   
                else
                        ViewBag.listCustomerTerritory = servicio.ObtenerClientesNombrePais(keyword);

            return View("Index");
        }
    }
}

MVCLab2/Views/Territory/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
        
    <h3>Lista Territorios</h3>
@using (Html.BeginForm("Search", "Territory")) //este es el cambio
{
    <input type="text" name="keyword" /> <input type="submit" value="Search" />
    <br />
    <input type="radio" name="condition" value="All" checked="checked" /> <span>All</span>
    <input type="radio" name="condition" value="byID"   /> <span>NombreCliente</span>
    <input type="radio" name="condition" value="byDate" />  <span>NombreTerritorio</span>
}
    <table cellpadding="2" cellspacing="2" border="1">
        <tr>
            <th>PersonID</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Territorio</th>
        </tr>
        @foreach (var CustomerTerritory in ViewBag.listCustomerTerritory) 
        { 
            <tr>
                <td>@CustomerTerritory.PersonID</td>
                <td>@CustomerTerritory.Nombre</td>
                <td>@CustomerTerritory.Apellido</td>
                <td>@CustomerTerritory.Territorio</td>
            </tr>
        }
    </table>
</body>
</html>